### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shenxiangzhuang** [shenxiangzhuang/shinstagram#3]
- [ ] fastapi + hf for ai services: text-complementation(qwen), text-to-image(flux)
- [ ] change to use local ai services and db services
- [ ] docker compose config
- [ ] start by loading characters config file
